# Generated by Django 3.0 on 2020-01-07 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_translations'),
    ]

    operations = [
        migrations.AddField(
            model_name='producttranslation',
            name='short_description',
            field=models.TextField(default='short description', max_length=250),
            preserve_default=False,
        ),
    ]
